-- AlterTable
ALTER TABLE "Child" ADD COLUMN     "dueDate" TIMESTAMP(3),
ALTER COLUMN "firstName" DROP NOT NULL,
ALTER COLUMN "lastName" DROP NOT NULL,
ALTER COLUMN "dob" DROP NOT NULL,
ALTER COLUMN "sex" DROP NOT NULL,
ALTER COLUMN "ethnicity" DROP NOT NULL;
